import type { Metadata } from "next";
import { Baloo_2 } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeScript } from "./theme-script";
import "./globals.css";

const baloo2 = Baloo_2({
  variable: "--font-baloo-2",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${baloo2.variable} antialiased`}>
        <ThemeScript />
        <ThemeProvider defaultTheme="dark" storageKey="entarat-theme">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
