 // List of 24 avatars for the selection grid
 export const AVATARS = [
  "/avatars/avatar-blue-square.svg",
  "/avatars/avatar-blue-square-2.svg",
  "/avatars/avatar-blue-square-3.svg",
  "/avatars/avatar-cyan-square.svg",
  "/avatars/avatar-cyan-square-2.svg",
  "/avatars/avatar-cyan-square-3.svg",
  "/avatars/avatar-green-square.svg",
  "/avatars/avatar-green-square-2.svg",
  "/avatars/avatar-orange-square.svg",
  "/avatars/avatar-orange-square-2.svg",
  "/avatars/avatar-pink-square.svg",
  "/avatars/avatar-pink-square-2.svg",
  "/avatars/avatar-purple-square.svg",
  "/avatars/avatar-purple-square-2.svg",
  "/avatars/avatar-red-square.svg",
  "/avatars/avatar-red-square-2.svg",
  "/avatars/avatar-red-square-3.svg",
  "/avatars/avatar-teal-square.svg",
  "/avatars/avatar-teal-square-2.svg",
  "/avatars/avatar-yellow-square.svg",
  "/avatars/avatar-yellow-square-2.svg",
  "/avatars/avatar-gradient-square.svg",
  "/avatars/avatar-cyan-square-variant.svg",
  "/avatars/avatar-placeholder-gray-1.svg",
];